name: Docker build and publish to AWS ECR

on:
  release:
    types: 
      - published

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-dev:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-dev')
    uses: siri-aws-web-app/thoth-workflows/.github/workflows/docker-build-publish.yml@v1.0.6
    with:
      AWS_REGION: "eu-central-1"
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::360532638835:role/github-norns"
      ECR_URI: "360532638835.dkr.ecr.eu-central-1.amazonaws.com/norns-weather-service-development"

  build-and-publish-stag:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-stag')
    uses: siri-aws-web-app/thoth-workflows/.github/workflows/docker-build-publish.yml@v1.0.6
    with:
      AWS_REGION: "eu-central-1"
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::525284627566:role/github-norns"
      ECR_URI: "525284627566.dkr.ecr.eu-central-1.amazonaws.com/norns-weather-service-staging"

  build-and-publish-prod:
    if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-dev') && !endsWith(github.ref, '-stag')
    uses: siri-aws-web-app/thoth-workflows/.github/workflows/docker-build-publish.yml@v1.0.6
    with:
      AWS_REGION: "eu-central-1"
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::875944587789:role/github-norns"
      ECR_URI: "875944587789.dkr.ecr.eu-central-1.amazonaws.com/norns-weather-service-production"
