# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: Docker build and publish to AWS ECR

on:
  release:
    types: 
      - published

env:
  AWS_REGION: "eu-central-1"

jobs:
  call-build-and-publish-dev:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-dev')
    uses: siri-aws-web-app/.github/workflow-templates/docker-build-publish.yml@v1.0.1
    with:
      AWS_REGION: $AWS_REGION
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::360532638835:role/github-norns"
      ECR_URI: "360532638835.dkr.ecr.eu-central-1.amazonaws.com/norns-weather-service-development"